name: Update Submodules

on:
  workflow_dispatch: 
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'  # 每天UTC时间0:00执行

jobs:
  update-submodules:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Update Submodules
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions"
          git submodule add https://github.com/Leon03/ZeroTierOne.git externals/core
          git submodule update --remote --merge
          git add .
          git commit -m "Update submodules"
          git push
